baseURL = "https://objective-bassi-9d4294.netlify.com/"
baseurl = "/"
title = "James C. Borders"
copyright = "&copy; 2019 James C. Borders"
languageCode = "en-us"
theme = "hugo-academic"
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
